kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.env_id }}-{{ .Values.app_name }}-extnme-svc
spec:
  type: ExternalName
  externalName: {{ .Values.app_name }}-svc.{{ .Values.env_ns }}.svc.cluster.local
  ports:
  - port: {{ .Values.app_container_port }}
